// Structured definitions for the hospital's 16 printed A4 lab report formats.
// A LabOrder is matched to one of these by exact CatalogItem name (LabOrder.tests
// is set to item.name at order time — see backend/app/services/counter_service.py
// lab_order()). Orders for any other lab item fall back to the plain free-text
// result box in LabCounterPage.tsx.

export type LabRow =
  | { kind: 'section'; label: string }
  | { kind: 'row'; id: string; label: string; unit?: string; range?: string; remark?: string }
  | { kind: 'row2'; id: string; label: string; col1: string; col2: string }
  | { kind: 'text'; id: string; label: string }
  | { kind: 'checkboxGroup'; id: string; label: string; options: string[] }
  | { kind: 'info'; headers: string[]; rows: string[][] }

export type LabTemplate = {
  name: string
  patientLabel?: string
  hasUnit: boolean
  hasRange: boolean
  rows: LabRow[]
  footnotes?: string[]
  // Some panels' printed footnotes include a "Confirmation will be
  // necessary." line that only applies when a screening test came back
  // positive — the lab tech ticks a checkbox when entering the result, and
  // only then does that line print (see LabTemplateResult.tsx).
  hasConfirmationNote?: boolean
}

function row(id: string, label: string, unit?: string, range?: string, remark?: string): LabRow {
  return { kind: 'row', id, label, unit, range, remark }
}
function section(label: string): LabRow {
  return { kind: 'section', label }
}

export const LAB_TEMPLATES: LabTemplate[] = [
  {
    name: 'General Physician Panel',
    hasUnit: true,
    hasRange: true,
    rows: [
      row('hpylori', 'H.Pylori Ab'),
      row('bilirubin', 'Serum Bilirubin', 'mg/dl', '< 13'),
      row('hba1c', 'HbA1C', '%', '< 6.5'),
      row('ldh', 'LDH', 'U/L', '132 - 248', 'IFCC Method'),
      row('rbs', 'RBS (Glucometer)', 'mg/dL', '81 - 180'),
      row('troponin', 'Troponin T', 'ng/ml', '0 - 0.1'),
      row('ospt', 'OSPT', 'sec', '10.0 - 14'),
      row('inr', 'INR', '', '0.7 - 1.3'),
      row('aptt', 'APTT', 'sec', '22 - 38'),
      row('esr', 'ESR', 'mm/1st hr', 'Male: 3-5 / Female: 4-7'),
      row('salb', 'Serum Albumin', 'g/dL', '3.5 - 5.2'),
      row('urea_sp', 'Urea (Serum/Plasma)', 'mg/dL', '10 - 50'),
      row('urea_urine', 'Urea (Urine)', 'gm/24 hr', '20 - 35'),
      row('creatinine', 'Creatinine', 'mg/dl', 'Adult male: 0.9-1.3 / Adult female: 0.6-1.2 (see full chart on file)'),
      row('calcium', 'Calcium', 'mg/dL', '8.6 - 10.3'),
      row('magnesium', 'Magnesium', 'mg/dL', '1.6 - 2.6'),
      row('amylase_sp', 'Amylase (Serum/Plasma)', 'U/L', '25 - 86'),
      row('amylase_urine', 'Amylase (Urine)', '', '< 470'),
      row('ft3', 'Free T3', 'pmol/L', '2.8 - 7.1'),
      row('ft4', 'Free T4', 'pmol/L', '12.0 - 22.0'),
      row('tsh', 'TSH', 'mIU/L', '0.3 - 4.2'),
      row('tt3', 'Total T3', 'nmol/L', '1.34 - 2.73'),
      row('tt4', 'Total T4', 'nmol/L', '78.3 - 157.4'),
      row('ddimer', 'D-Dimer', 'mg/L', '0 - 0.5'),
      row('crp_q', 'CRP (Quali)', 'mg/L', '< 6'),
      row('crp_quant', 'CRP (Quanti)', 'mg/L', '< 10'),
      row('hscrp', 'hs CRP', 'mg/L', '< 1.0'),
      row('uric', 'Uric Acid', 'mg/dl', '2.6 - 6.0'),
      row('aso', 'ASO (titre)', 'IU/mL', '< 200'),
      section('Electrolyte'),
      row('sodium', 'Sodium', 'mmol/L', '136 - 145'),
      row('potassium', 'Potassium', 'mmol/L', '3.5 - 5.2'),
      row('chloride', 'Chloride', 'mmol/L', '96 - 108'),
      row('bicarb', 'Bicarbonate', 'mmol/L', '24 - 30'),
      section('Total Protein & Differential (T & DP)'),
      row('tprotein', 'Total Protein', 'g/L', '60 - 78'),
      row('albumin', 'Albumin', 'g/L', '35 - 52'),
      row('globulin', 'Globulin', 'g/L', '20 - 39'),
      section('Lipid Profile'),
      row('tchol', 'Total Cholesterol', 'mg/dL', 'Desirable: < 200'),
      row('trig', 'Triglyceride', 'mg/dL', 'Male: 60-165 / Female: 40-140'),
      row('hdl', 'HDL', 'mg/dL', 'Male: 35-80 / Female: 42-88'),
      row('ldl', 'LDL (Direct)', 'mg/dL', '< 130'),
      section('Liver Function Test'),
      row('tbili', 'Total Bilirubin', 'mg/dl', 'Adult up to: 1.2 / Infant: 0.2-8'),
      row('alp', 'Alkaline Phosphatase', 'U/L', 'Men: 80-306 / Women: 64-306 / Child: 180-1200'),
      row('sgpt', 'SGPT (ALT)', 'U/L', 'Men up to 45 / Women up to 35'),
      row('sgot', 'SGOT (AST)', 'U/L', 'Men up to 35 / Women up to 31'),
      row('ra', 'RA (Quali)'),
      row('ana', 'ANA (Quali)'),
      row('hbsag1', 'HBs Ag', '', '', 'ACE Bio'),
      row('hcvab1', 'HCV Ab', '', '', 'ACE Bio'),
      row('hivab1', 'HIV Ab', '', '', 'ACE Bio'),
      row('vdrl1', 'VDRL', '', '', 'ACE Bio'),
      section('Dengue Duo (ICT)'),
      row('dengue_ns1', 'NS1Ag'),
      row('dengue_igg', 'IgG'),
      row('dengue_igm', 'IgM'),
      row('mp_ict', 'MP (ICT)'),
      row('mp_film', 'MP (Film)'),
      row('psa', 'PSA (Total)', 'ng/ml', 'Normal level: < 4'),
      row('ketone', 'Blood Ketone', 'mmol/L', '< 0.6'),
      row('u_albumin', 'Urine Albumin', 'mg/dl', '<= 2'),
      row('u_for_albumin', 'Urine for Albumin'),
      row('afp', 'AFP', 'ng/ml', 'Normal level: 0 - 20'),
      row('cea', 'CEA', 'ng/ml', '0 - 5.0'),
      row('abo', 'ABO Grouping'),
      row('rh', 'Rh Grouping'),
      row('bleeding', 'Bleeding Time', 'min', '2 - 5'),
      row('clotting', 'Clotting Time', 'min', '2 - 7'),
      row('egfr', 'Serum Creatinine eGFR', 'ml/min/1.73m2', '> 90'),
      row('retic', 'Reticulocyte Count', '%', '0.2 - 2'),
      section("Coomb's Test"),
      row('direct_coombs', "Direct Coomb's Test"),
      row('indirect_coombs', "Indirect Coomb's Test"),
      section("Coomb's Test (Temperature Specific)"),
      row('direct_4c', 'Direct 4°C'),
      row('direct_37c', 'Direct 37°C'),
      row('indirect_4c', 'Indirect 4°C'),
      row('indirect_37c', 'Indirect 37°C'),
      row('u_for_ucg', 'Urine for UCG'),
      row('ca125', 'CA-12-5', 'U/mL', '0 - 35'),
      row('ca153', 'CA-15-3', 'U/mL', '< 31.3'),
      row('ca199', 'CA-19-9', 'U/mL', '< 35'),
      row('hbsab_quanti', 'HBs Ab (Quanti)', 'mIU/ml', '> 10'),
      row('tpha', 'TPHA'),
      section('HBV Profile'),
      row('hbsag2', 'HBsAg'),
      row('hbsab2', 'HBsAb'),
      row('hbeag', 'HBeAg'),
      row('hbeab', 'HBeAb'),
      row('hbcab', 'HBcAb'),
      section('TB (ICT)'),
      row('tb_igg', 'IgG'),
      row('tb_igm', 'IgM'),
      row('g6pd', 'G6PD (Quantitative)', 'U/g Hb', '> 4.6'),
      section('Iron Study'),
      row('ferritin', 'Ferritin', 'ng/ml', 'Male: 20-250 / Female: 20-200 / Child: 15-150'),
      row('iron', 'Iron', 'ug/dl', 'Male: 70-180 / Female: 60-180 / Child: 50-120'),
      row('tibc', 'TIBC', 'ug/dl', 'Male: 171-505 / Female: 149-492 / Child: 240-450'),
      row('tsat', 'Transferrin Saturation Rate', '%', '20 - 60'),
      row('dbili', 'Direct Bilirubin', 'mg/dl', '< 0.3'),
      row('indbili', 'Indirect Bilirubin', 'mmol/L', '0.2 - 8.0'),
      section('Vitamin D'),
      row('vitd', 'Vitamin D', 'ng/ml', 'Deficient < 20 / Insufficient 20-29 / Sufficient 30-100 / Toxicity > 100'),
      section('OGTT (Plasma Glucose)'),
      row('ogtt_fasting', 'Fasting', 'mg/dL', '< 95'),
      row('ogtt_1hr', '1 hr. after glucose', 'mg/dL', '< 180'),
      row('ogtt_2hr', '2 hr. after glucose', 'mg/dL', '0 - 140'),
      row('occult_blood', 'Stool For Occult Blood', '', 'Positive / Negative'),
    ],
    footnotes: [
      'Please correlate with clinical condition.',
      'Recollected second sample if needed confirmation.',
    ],
    hasConfirmationNote: true,
  },
  {
    name: 'OG Panel',
    hasUnit: true,
    hasRange: true,
    rows: [
      row('rbs', 'RBS (Glucometer)', 'mg/dL', '81 - 180'),
      row('abo', 'ABO Grouping'),
      row('rh', 'Rh Grouping'),
      row('bleeding', 'Bleeding Time', 'min', '2 - 5'),
      row('clotting', 'Clotting Time', 'min', '2 - 7'),
      row('hbsag', 'HBs Ag', '', '', 'ACE Bio'),
      row('hcvab', 'HCV Ab', '', '', 'ACE Bio'),
      row('hivab', 'HIV Ab', '', '', 'ACE Bio'),
      row('vdrl', 'VDRL', '', '', 'ACE Bio'),
    ],
    hasConfirmationNote: true,
  },
  {
    name: 'BCRVD Screening (HBsAg, HCV, HIV, VDRL)',
    hasUnit: false,
    hasRange: true,
    rows: [
      row('hbsag', 'HBsAg', '', 'ACE Bio'),
      row('hcvab', 'HCV Ab', '', 'ACE Bio'),
      row('hivab', 'HIV Ab', '', 'ACE Bio'),
      row('vdrl', 'VDRL', '', 'ACE Bio'),
    ],
    hasConfirmationNote: true,
  },
  {
    name: 'ABO and Rh Blood Grouping',
    hasUnit: false,
    hasRange: false,
    rows: [
      row('abo', 'ABO Grouping'),
      row('rh', 'Rh Grouping'),
    ],
  },
  {
    name: 'Beta hCG',
    hasUnit: true,
    hasRange: true,
    rows: [
      row('betahcg', 'Beta hCG', 'mIU/mL', 'See below'),
      { kind: 'text', id: 'impression', label: 'Impression' },
      {
        kind: 'info',
        headers: ['Gestational Age', 'Beta hCG Range (mIU/mL)'],
        rows: [
          ['Non-pregnant female', '< 5'],
          ['3 week', '5 - 50'],
          ['4 week', '5 - 426'],
          ['5 week', '18 - 4340'],
          ['6 week', '1080 - 56500'],
          ['7-8 week', '7650 - 229000'],
          ['9-12 week', '25700 - 288000'],
          ['13-16 week', '13300 - 254000'],
          ['17-24 week', '4060 - 165400'],
          ['25-40 week', '3640 - 117000'],
        ],
      },
    ],
  },
  {
    name: 'Urine Routine Examination',
    hasUnit: false,
    hasRange: true,
    rows: [
      section('Urine Analysis'),
      row('leu', 'Leukocytes (LEU)', '', '9 - 15 Leu/ul'),
      row('nit', 'Nitride (NIT)', '', '0.05 - 0.1 mg/dL'),
      row('uro', 'Urobilinogen (URO)', '', '3.5 - 17 umol/L'),
      row('pro', 'Protein (PRO)', '', '0.075 - 0.15 g/L'),
      row('ph', 'pH', '', '5.0 - 9.0'),
      row('blo', 'Blood (BLO)', '', '5 - 10 Ery/ul'),
      row('sg', 'Specific Gravity (SG)', '', '1.000 - 1.030'),
      row('ket', 'Ketone (KET)', '', '0.25 - 0.5 mmol/L'),
      row('bil', 'Bilirubin (BIL)', '', '6.8 - 17 umol/L'),
      row('glu', 'Glucose (GLU)', '', '2.5 - 5 mmol/L'),
      row('asc', 'Ascorbic Acid (ASC)', '', '0.28 - 0.56 mmol/L'),
      section('Microscopic Examination'),
      row('appearance', 'Appearance'),
      row('epithelial', 'Epithelial Cells', '/HPF'),
      row('pus', 'Pus Cells', '/HPF'),
      row('rbcs', 'RBCs', '/HPF'),
      row('casts', 'Casts'),
      row('crystals', 'Crystals'),
      row('others', 'Others'),
    ],
  },
  {
    name: 'Blood Donor Issue Form',
    patientLabel: "Donor Name",
    hasUnit: true,
    hasRange: true,
    rows: [
      row('hb', 'Hb%', 'g/dL', 'Male: 12.5-15.5 / Female: 11.5-14.5'),
      row('abo', 'ABO Grouping'),
      row('rh', 'Rh Grouping'),
      row('hbsag', 'HBsAg', '', '', 'ACE Bio'),
      row('hcvab', 'HCV Antibody', '', '', 'Intec'),
      row('hivab', 'HIV Antibody', '', '', 'Intec'),
      row('vdrl', 'VDRL', '', '', 'Intec'),
      { kind: 'text', id: 'crossmatch', label: "Cross-matching remarks (patient's name, age, sex, admission no., blood group, major/minor cross matching result)" },
    ],
  },
  {
    name: 'RPR Dilution (VDRL Titre)',
    hasUnit: false,
    hasRange: false,
    rows: [
      section('VDRL Dilution (Rapid Plasma Reagin Test)'),
      row('neat', 'Neat'),
      row('d2', 'RPR (1 in 2 dilution)'),
      row('d4', 'RPR (1 in 4 dilution)'),
      row('d8', 'RPR (1 in 8 dilution)'),
      row('d16', 'RPR (1 in 16 dilution)'),
      row('d32', 'RPR (1 in 32 dilution)'),
      row('d64', 'RPR (1 in 64 dilution)'),
      row('d128', 'RPR (1 in 128 dilution)'),
    ],
    footnotes: ['*** END OF REPORT ***'],
  },
  {
    name: 'Widal Test',
    hasUnit: false,
    hasRange: false,
    rows: [
      { kind: 'row2', id: 'styphi', label: 'Sal. Typhi', col1: 'O Antibody', col2: 'H Antibody' },
      { kind: 'row2', id: 'sparaa', label: 'Sal. Para Typhi A', col1: 'O Antibody', col2: 'H Antibody' },
      { kind: 'row2', id: 'sparab', label: 'Sal. Para Typhi B', col1: 'O Antibody', col2: 'H Antibody' },
    ],
    footnotes: ['*** END OF REPORT ***'],
  },
  {
    name: 'Semen Analysis',
    hasUnit: true,
    hasRange: true,
    rows: [
      section('Macroscopic Examination'),
      row('volume', 'Volume', 'mL', '> 1.5'),
      row('liquefaction', 'Liquefaction Time', 'minutes after collection', 'Complete by 30 mins.'),
      row('color', 'Color', '', 'Grey-White'),
      row('viscosity', 'Viscosity'),
      row('ph', 'PH', '', '7.2 - 8.0'),
      section('Microscopic Examination'),
      row('sperm_count', 'Sperm count', 'million sperm / mL', '15 - 200'),
      section('Sperm Motility'),
      row('active', 'Active', '%'),
      row('sluggish', 'Sluggish', '%'),
      row('dead', 'Dead', '%'),
      section('Sperm Morphology'),
      row('normal_head', 'Normal Head', '%'),
      row('small_head', 'Small Head', '%'),
      row('giant_head', 'Giant Head', '%'),
      row('pus', 'Pus Cells'),
      row('others', 'Others'),
      { kind: 'checkboxGroup', id: 'remarks', label: 'Remarks', options: ['Normospermia', 'Oligozoospermia', 'Azoospermia'] },
    ],
  },
  {
    name: 'Sputum and Stool AFB',
    hasUnit: false,
    hasRange: false,
    rows: [
      row('day1', 'Sputum for AFB (1st day)'),
      row('day2', 'Sputum for AFB (2nd day)'),
      row('day3', 'Sputum for AFB (3rd day)'),
      row('stool', 'Stool for AFB'),
    ],
  },
  {
    name: 'Stool Routine Examination',
    hasUnit: false,
    hasRange: false,
    rows: [
      section('Macroscopic Examination'),
      row('appearance', 'Appearance'),
      row('consistency', 'Consistency'),
      row('mucous', 'Mucous'),
      row('blood', 'Blood'),
      section('Microscopic Examination'),
      row('pus', 'Pus Cell'),
      row('rbcs', 'RBCs'),
      row('ova', 'Ova'),
      row('cyst', 'Cyst'),
      row('others', 'Others'),
    ],
  },
  {
    name: 'ADA (Adenosine Deaminase)',
    hasUnit: true,
    hasRange: true,
    rows: [
      row('specimen', 'Type of Specimen'),
      row('ada', 'ADA', 'U/L'),
      {
        kind: 'info',
        headers: ['Type of Specimen', 'Cut-off Value', 'Sensitivity %', 'Specificity %'],
        rows: [
          ['Pleural Fluid', '36 - 45', '78 %', '85 % - 95 %'],
          ['Pericardial Fluid', '36 - 45', '78 %', '85 % - 95 %'],
          ['Ascites Fluid', '36 - 45', '100 %', '97 %'],
          ['CSF', '9 - 10', '50 % - 80 %', '85 % - 95 %'],
          ['Serum', '24', '35 %', '91 %'],
          ['Sputum', '93', '90 % - 95%', '90 % - 95%'],
        ],
      },
    ],
  },
  {
    name: 'Urine Albumin Creatinine Ratio (UACR)',
    hasUnit: true,
    hasRange: true,
    rows: [
      row('u_albumin', 'Urine Albumin', 'mg/dL', '<= 2'),
      row('u_creatinine', 'Urine Creatinine', 'mg/dL', '29 - 226'),
      row('uacr', 'Urine Albumin Creatinine Ratio', 'mg/g', '< 30'),
      {
        kind: 'info',
        headers: ['Category', 'ACR (mg/g)', 'Terms'],
        rows: [
          ['A1', '< 30 mg/g', 'Normal to mildly increased'],
          ['A2', '30 - 300 mg/g', 'Moderately increased'],
          ['A3', '> 300 mg/g', 'Severely increased'],
        ],
      },
    ],
    footnotes: ['*** END OF REPORT ***'],
  },
  {
    name: 'Urine Protein Creatinine Ratio (UPCR)',
    hasUnit: true,
    hasRange: true,
    rows: [
      row('u_protein', 'Urine Protein', 'mg/dL', '<= 15'),
      row('u_creatinine', 'Urine Creatinine', 'mg/dL', '29 - 226'),
      row('upcr', 'Urine Protein Creatinine Ratio', 'mg/mg', '< 0.15'),
      { kind: 'text', id: 'comment', label: 'Comment' },
      {
        kind: 'info',
        headers: ['Ratio', 'Interpretation'],
        rows: [
          ['Less than 0.2', 'Normal range'],
          ['0.2 - 3.5', 'Moderately increased'],
          ['More than 3.5', 'Increased'],
        ],
      },
    ],
    footnotes: ['*** END OF REPORT ***'],
  },
  {
    name: 'Blood Film Report',
    hasUnit: false,
    hasRange: false,
    rows: [
      { kind: 'text', id: 'rbcs', label: 'RBCs' },
      { kind: 'text', id: 'wbcs', label: 'WBCs' },
      { kind: 'text', id: 'platelets', label: 'Platelets' },
    ],
  },
]

export function findLabTemplate(testName: string): LabTemplate | undefined {
  return LAB_TEMPLATES.find((t) => t.name === testName)
}
